apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-elasticsearch
  namespace: echo
  labels:
    app: echo-elasticsearch
    component: search
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echo-elasticsearch
  template:
    metadata:
      labels:
        app: echo-elasticsearch
        component: search
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9114'
        prometheus.io/path: '/metrics'
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
        - name: configure-sysctl
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            privileged: true
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
        - name: volume-mount-hack
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.name
              value: 'echo-cluster'
            - name: discovery.type
              value: 'single-node'
            - name: bootstrap.memory_lock
              value: 'true'
            - name: ES_JAVA_OPTS
              value: '-Xms1g -Xmx1g'
            - name: xpack.security.enabled
              value: 'false'
            - name: xpack.security.enrollment.enabled
              value: 'false'
            - name: xpack.security.http.ssl.enabled
              value: 'false'
            - name: xpack.security.transport.ssl.enabled
              value: 'false'
            - name: xpack.ml.enabled
              value: 'false'
            - name: xpack.monitoring.collection.enabled
              value: 'true'
            - name: path.data
              value: '/usr/share/elasticsearch/data'
            - name: path.logs
              value: '/usr/share/elasticsearch/logs'
            - name: network.host
              value: '0.0.0.0'
            - name: http.port
              value: '9200'
            - name: transport.port
              value: '9300'
            - name: indices.query.bool.max_clause_count
              value: '10000'
            - name: search.max_buckets
              value: '100000'
            - name: action.destructive_requires_name
              value: 'true'
          resources:
            requests:
              memory: '2Gi'
              cpu: '500m'
            limits:
              memory: '4Gi'
              cpu: '2000m'
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow&timeout=5s
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              readOnly: true
        - name: elasticsearch-exporter
          image: prometheuscommunity/elasticsearch-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9114
              protocol: TCP
          env:
            - name: ES_URI
              value: 'http://localhost:9200'
            - name: ES_ALL
              value: 'true'
            - name: ES_INDICES
              value: 'true'
            - name: ES_INDICES_SETTINGS
              value: 'true'
            - name: ES_SHARDS
              value: 'true'
            - name: ES_SNAPSHOTS
              value: 'true'
            - name: ES_TIMEOUT
              value: '30s'
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '128Mi'
              cpu: '100m'
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: echo-elasticsearch-pvc
        - name: elasticsearch-config
          configMap:
            name: echo-elasticsearch-config
      nodeSelector:
        echo.io/node-type: 'search'
      tolerations:
        - key: 'echo.io/dedicated'
          operator: 'Equal'
          value: 'search'
          effect: 'NoSchedule'
---
apiVersion: v1
kind: Service
metadata:
  name: echo-elasticsearch-service
  namespace: echo
  labels:
    app: echo-elasticsearch
    component: search
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9114'
    prometheus.io/path: '/metrics'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: http
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: transport
      protocol: TCP
    - name: metrics
      port: 9114
      targetPort: metrics
      protocol: TCP
  selector:
    app: echo-elasticsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echo-elasticsearch-pvc
  namespace: echo
  labels:
    app: echo-elasticsearch
    component: search
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-elasticsearch-config
  namespace: echo
  labels:
    app: echo-elasticsearch
    component: search
data:
  elasticsearch.yml: |
    # Elasticsearch configuration for Echo application

    # Cluster settings
    cluster.name: echo-cluster
    node.name: ${node.name}

    # Network settings
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300

    # Discovery settings
    discovery.type: single-node

    # Path settings
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs

    # Memory settings
    bootstrap.memory_lock: true

    # Security settings (disabled for development)
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false

    # Machine Learning (disabled to save resources)
    xpack.ml.enabled: false

    # Monitoring
    xpack.monitoring.collection.enabled: true

    # Index settings
    action.destructive_requires_name: true

    # Query settings
    indices.query.bool.max_clause_count: 10000
    search.max_buckets: 100000

    # Thread pool settings
    thread_pool:
      search:
        size: 4
        queue_size: 1000
      index:
        size: 4
        queue_size: 200
      bulk:
        size: 4
        queue_size: 50

    # Index template for Echo data
    index:
      number_of_shards: 1
      number_of_replicas: 0
      refresh_interval: 1s
      max_result_window: 10000

    # Logging
    logger:
      level: INFO
      org.elasticsearch.discovery: DEBUG

    # HTTP settings
    http:
      max_content_length: 100mb
      max_initial_line_length: 4kb
      max_header_size: 8kb
      compression: true
      cors:
        enabled: true
        allow-origin: "*"
        allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
        allow-headers: X-Requested-With, Content-Type, Content-Length, Authorization

    # Circuit breaker settings
    indices.breaker.total.limit: 70%
    indices.breaker.fielddata.limit: 40%
    indices.breaker.request.limit: 40%

    # Cache settings
    indices.queries.cache.size: 10%
    indices.fielddata.cache.size: 20%

    # Indexing settings
    index.store.type: fs
    index.store.fs.fs_lock: native

    # Cluster routing
    cluster.routing.allocation.disk.threshold_enabled: true
    cluster.routing.allocation.disk.watermark.low: 85%
    cluster.routing.allocation.disk.watermark.high: 90%
    cluster.routing.allocation.disk.watermark.flood_stage: 95%

    # Node settings
    node.data: true
    node.master: true
    node.ingest: true

    # Gateway settings
    gateway.recover_after_nodes: 1
    gateway.expected_nodes: 1

    # Recovery settings
    cluster.routing.allocation.node_concurrent_recoveries: 2
    cluster.routing.allocation.node_initial_primaries_recoveries: 4
    indices.recovery.max_bytes_per_sec: 40mb

    # Translog settings
    index.translog.flush_threshold_size: 512mb
    index.translog.sync_interval: 5s

    # Merge settings
    index.merge.scheduler.max_thread_count: 1

    # Slow log settings
    index.search.slowlog.threshold.query.warn: 10s
    index.search.slowlog.threshold.query.info: 5s
    index.search.slowlog.threshold.query.debug: 2s
    index.search.slowlog.threshold.query.trace: 500ms

    index.search.slowlog.threshold.fetch.warn: 1s
    index.search.slowlog.threshold.fetch.info: 800ms
    index.search.slowlog.threshold.fetch.debug: 500ms
    index.search.slowlog.threshold.fetch.trace: 200ms

    index.indexing.slowlog.threshold.index.warn: 10s
    index.indexing.slowlog.threshold.index.info: 5s
    index.indexing.slowlog.threshold.index.debug: 2s
    index.indexing.slowlog.threshold.index.trace: 500ms
