# Development-specific service patches
apiVersion: v1
kind: Service
metadata:
  name: echo-nginx-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-app-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
      protocol: TCP
    - name: dev-server
      port: 3000
      targetPort: 3000
      nodePort: 30030
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-postgres-service
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-redis-service
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 30379
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-grafana-service
spec:
  type: NodePort
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30300
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-prometheus-service
spec:
  type: NodePort
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 30090
      protocol: TCP
