# Prometheus configuration for Echo application monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'echo-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Echo application metrics
  - job_name: 'echo-app'
    static_configs:
      - targets: ['echo-app:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node exporter for system metrics (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom application metrics
  - job_name: 'echo-custom-metrics'
    static_configs:
      - targets: ['echo-app:9000']
    scrape_interval: 15s
    metrics_path: /custom-metrics
    scrape_timeout: 10s
    honor_labels: true

  # WebRTC metrics
  - job_name: 'echo-rtc-metrics'
    static_configs:
      - targets: ['echo-app:8080']
    scrape_interval: 10s
    metrics_path: /rtc-metrics
    scrape_timeout: 5s

  # Audio processing metrics
  - job_name: 'echo-audio-metrics'
    static_configs:
      - targets: ['echo-app:3000']
    scrape_interval: 10s
    metrics_path: /audio-metrics
    scrape_timeout: 5s

  # Translation service metrics
  - job_name: 'echo-translation-metrics'
    static_configs:
      - targets: ['echo-app:3000']
    scrape_interval: 15s
    metrics_path: /translation-metrics
    scrape_timeout: 10s
# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "username"
#       password: "password"
