# Production-specific deployment patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: echo-app
          env:
            - name: NODE_ENV
              value: 'production'
            - name: LOG_LEVEL
              value: 'info'
            - name: DEBUG_MODE
              value: 'false'
            - name: ENABLE_CORS
              value: 'false'
            - name: ENABLE_SWAGGER
              value: 'false'
            - name: METRICS_ENABLED
              value: 'true'
            - name: HEALTH_CHECK_ENABLED
              value: 'true'
            - name: RATE_LIMITING_ENABLED
              value: 'true'
            - name: COMPRESSION_ENABLED
              value: 'true'
            - name: WORKER_PROCESSES
              value: 'auto'
            - name: MAX_CONNECTIONS
              value: '1000'
            - name: KEEP_ALIVE_TIMEOUT
              value: '65'
          resources:
            requests:
              memory: '1Gi'
              cpu: '500m'
            limits:
              memory: '2Gi'
              cpu: '1000m'
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - echo-app
                topologyKey: kubernetes.io/hostname

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-postgres
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: postgres
          env:
            - name: POSTGRES_SHARED_PRELOAD_LIBRARIES
              value: 'pg_stat_statements,pg_buffercache'
            - name: POSTGRES_MAX_CONNECTIONS
              value: '200'
            - name: POSTGRES_SHARED_BUFFERS
              value: '256MB'
            - name: POSTGRES_EFFECTIVE_CACHE_SIZE
              value: '1GB'
            - name: POSTGRES_MAINTENANCE_WORK_MEM
              value: '64MB'
            - name: POSTGRES_CHECKPOINT_COMPLETION_TARGET
              value: '0.9'
            - name: POSTGRES_WAL_BUFFERS
              value: '16MB'
            - name: POSTGRES_DEFAULT_STATISTICS_TARGET
              value: '100'
          resources:
            requests:
              memory: '2Gi'
              cpu: '1000m'
            limits:
              memory: '4Gi'
              cpu: '2000m'
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-redis
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: redis
          env:
            - name: REDIS_MAXMEMORY
              value: '768mb'
            - name: REDIS_MAXMEMORY_POLICY
              value: 'allkeys-lru'
          command:
            - redis-server
            - --maxmemory
            - 768mb
            - --maxmemory-policy
            - allkeys-lru
            - --save
            - '900 1'
            - --save
            - '300 10'
            - --save
            - '60 10000'
            - --appendonly
            - 'yes'
            - --appendfsync
            - 'everysec'
            - --tcp-keepalive
            - '300'
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-elasticsearch
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: elasticsearch
          env:
            - name: ES_JAVA_OPTS
              value: '-Xms2g -Xmx2g'
            - name: discovery.type
              value: 'single-node'
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: 'false'
            - name: bootstrap.memory_lock
              value: 'true'
            - name: indices.memory.index_buffer_size
              value: '30%'
            - name: indices.memory.min_index_buffer_size
              value: '96mb'
          resources:
            requests:
              memory: '3Gi'
              cpu: '1000m'
            limits:
              memory: '4Gi'
              cpu: '2000m'
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
        - name: nginx
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - echo-nginx
                topologyKey: kubernetes.io/hostname
