# Staging-specific service patches
apiVersion: v1
kind: Service
metadata:
  name: echo-nginx-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: 'nlb'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-app-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    prometheus.io/path: '/metrics'
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1800
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-postgres-service
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'false'
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
    - name: postgres-exporter
      port: 9187
      targetPort: 9187
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-redis-service
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'false'
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: redis-exporter
      port: 9121
      targetPort: 9121
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-elasticsearch-service
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'false'
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: 9300
      protocol: TCP
    - name: elasticsearch-exporter
      port: 9114
      targetPort: 9114
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-prometheus-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  type: ClusterIP
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: echo-grafana-service
spec:
  type: ClusterIP
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP
